name: A workflow for my Hello World file
on: push
jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Hello world action
    steps:
      - uses: actions/checkout@v1
      - uses:  ./action-a
        with:
          MY_NAME: "Mona"

